server:
  port: 8084

spring:
  application:
    name: API-GATEWAY


  cloud:
    gateway:
      routes:
        - id: POLICY-SERVICE
          uri: lb://POLICY-SERVICE
          predicates:
            - Path=/policies,/policies/{pId},/create

        - id: POLICY-SELECTION-SERVICE
          uri: lb://POLICY-SELECTION-SERVICE
          predicates:
            - Path=/policie/select,/getPolicySelectionById/{policySelectionId}

        - id: TRANSACTION-SERVICE
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/payments/{policySelectionId},/getById/{transactionId}

        - id: POLICY-GENERATION-SERVICE
          uri: lb://POLICY-GENERATION-SERVICE
          predicates:
            - Path=/policy/generate/**,/getDocumentById/{policyGenerationId}

        - id: NOTIFICATION-SERVICE
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path= /notification/email/{policyGenerationId}


management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      shows-details: always
  metrics:
    tags:
      application: API-GATEWAY

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka



